apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subscribers-app.fullname" . }}
  labels:
    {{- include "subscribers-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "subscribers-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "subscribers-app.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: {{ include "subscribers-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: AWS_REGION
              value: {{ .Values.aws_region }}
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: sqs-queue-connection
                  key: url
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http 