apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "subscribers-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "subscribers-app.labels" . | nindent 4 }} 