apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: subscribers-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/stavocha/no-more-dev-env-headaches
    targetRevision: main
    path: argocd/charts/subscribers-app
    helm:
      valueFiles:
        - values.yaml
        # - values-files/developer/values-daisy.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: subscribers-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 